<?xml version='1.0'?>
<ns2:test-suite xmlns:ns2='urn:model.allure.qatools.yandex.ru' start='1619001376774' stop='1619001399875'>
    <name>Simple Calculator </name>
    <title>Simple Calculator </title>
    <test-cases>
        <test-case start='1619001376776' status='failed' stop='1619001387566'>
            <name>Addition Of Numbers</name>
            <title>Addition Of Numbers</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
            <failure>
                <message>Expected 10 to equal 111.</message>
                <stack-trace>Error: Failed expectation
                    at F:\Synechron_Protractor\Training\protractor\development.js:28:29
                    at elementArrayFinder_.then (C:\Users\dell\AppData\Roaming\npm\node_modules\protractor\built\element.js:804:32)
                    at ManagedPromise.invokeCallback_ (C:\Users\dell\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1376:14)
                    at TaskQueue.execute_ (C:\Users\dell\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3084:14)
                    at TaskQueue.executeNext_ (C:\Users\dell\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3067:27)
                    at asyncRun (C:\Users\dell\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2927:27)
                    at C:\Users\dell\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:668:7
                    at process._tickCallback (internal/process/next_tick.js:68:7)</stack-trace>
            </failure>
        </test-case>
        <test-case start='1619001387567' status='failed' stop='1619001391361'>
            <name>Substraction Of Numbers</name>
            <title>Substraction Of Numbers</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
            <failure>
                <message>Expected 0 to equal 10.</message>
                <stack-trace>Error: Failed expectation
                    at F:\Synechron_Protractor\Training\protractor\development.js:42:29
                    at elementArrayFinder_.then (C:\Users\dell\AppData\Roaming\npm\node_modules\protractor\built\element.js:804:32)
                    at ManagedPromise.invokeCallback_ (C:\Users\dell\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1376:14)
                    at TaskQueue.execute_ (C:\Users\dell\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3084:14)
                    at TaskQueue.executeNext_ (C:\Users\dell\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3067:27)
                    at asyncRun (C:\Users\dell\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2927:27)
                    at C:\Users\dell\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:668:7
                    at process._tickCallback (internal/process/next_tick.js:68:7)</stack-trace>
            </failure>
        </test-case>
        <test-case start='1619001391361' status='passed' stop='1619001395704'>
            <name>Multiplication  Of Numbers</name>
            <title>Multiplication  Of Numbers</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
        </test-case>
        <test-case start='1619001395704' status='passed' stop='1619001399873'>
            <name>Division Of Numbers</name>
            <title>Division Of Numbers</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
        </test-case>
    </test-cases>
</ns2:test-suite>